name = "payment-gateway"
main = "src/midtrans-worker.js"
compatibility_date = "2026-06-12"
account_id = "0becfc9754d51754f5436cac5c1bfa5b"

[vars]
FRONTEND_URL = "https://ahmadfardan464-cmyk.github.io/ai-prompt-pack"
MIDTRANS_CLIENT_KEY = "***"
